### ISSUE TITLE
[Feature Request]: add `Done` func

### ISSUE THREAD

**Issue by BlackHole1** [Code-Hex/go-infinity-channel#1]
### Description

At present, `infinity` can meet most of our needs, but it lacks `Done()`. In our scenario: we will execute: `os.Exit(0)`, but because `infinity` will immediately consume the data, when executing `Out()`, it will be after `os.Exit(0)`, so the data will never be consumed.

### Example

```go
package main

import (
	"fmt"
	"os"
	"time"

	"github.com/Code-Hex/go-infinity-channel"
)

var channel *infinity.Channel[string]

func init() {
	channel = infinity.NewChannel[string]()
}

func channelHandler() {
	for i := range channel.Out() {
		// simulate a time-consuming operation.
		{
			time.Sleep(1 * time.Second)
			fmt.Println("Received:", i)
		}

		if i == "Exit" {
			channel.Close()
		}
	}
}

func main() {
	go channelHandler()

	doSomething()
	os.Exit(0) // => Never not print "Received: Exit"
}

func doSomething() {
	channel.In() <- "Do something"
	time.Sleep(2 * time.Second)
	channel.In() <- "Exit"
}
```

### My temporary solution

```go
package main

import (
	"fmt"
	"os"
	"time"

	"github.com/Code-Hex/go-infinity-channel"
)

var channel *infinity.Channel[string]

var waitClose = make(chan struct{})

func init() {
	channel = infinity.NewChannel[string]()
}

func channelHandler() {
	for i := range channel.Out() {
		// simulate a time-consuming operation.
		{
			time.Sleep(1 * time.Second)
			fmt.Println("Received:", i)
		}

		if i == "Exit" {
			channel.Close()
			waitClose <- struct{}{}
		}
	}
}

func main() {
	go channelHandler()

	doSomething()
	<-waitClose
	os.Exit(0)
}

func doSomething() {
	channel.In() <- "Do something"
	time.Sleep(2 * time.Second)
	channel.In() <- "Exit"
}
```

```diff
12a13,14
> var waitClose = make(chan struct{})
> 
26a29
> 			waitClose <- struct{}{}
35c38,39
< 	os.Exit(0) // => Never not print "Received: Exit"
---
> 	<-waitClose
> 	os.Exit(0)
```

**Comment by BlackHole1** [comment]
I am not sure if adding `Done` should fall under the responsibilities of `infinity`. If not, it's okay; I can continue using the temporary solution as well.

**Comment by Code-Hex** [comment]
@BlackHole1 Thanks for making a new issue!

Could you provide me more information why you need done method? I want to know the use case.

There are only three methods for normal channels as well: in, out, and close. Close is used to indicate completion.

---

Close should be called at the point where In is called. As you probably know, it is the same for normal channels to close when there is nothing to send. Using your code as an example, call Close instead of sending Exit

**Comment by BlackHole1** [comment]
Thank you for your reply. It might be that my initial expression was unclear; what I meant was: "A method is needed to wait for the consumer to complete."

If it takes 2 seconds for a consumer (ch.Out) to complete, there's currently no way for infinity to know when the consumer finishes.

---

> Close should be called at the point where In is called. As you probably know, it is the same for normal channels to close when there is nothing to send. Using your code as an example, call Close instead of sending Exit

According to your description, I have modified the code as follows:

```go
package main

import (
	"fmt"
	"os"
	"time"

	"github.com/Code-Hex/go-infinity-channel"
)

var channel *infinity.Channel[string]

func init() {
	channel = infinity.NewChannel[string]()
}

func channelHandler() {
	for i := range channel.Out() {
		// simulate a time-consuming operation.
		{
			time.Sleep(1 * time.Second)
			fmt.Println("Received:", i)
		}
	}
}

func main() {
	go channelHandler()

	doSomething()
	os.Exit(0)
}

func doSomething() {
	channel.In() <- "Do something"
	time.Sleep(2 * time.Second)
	channel.In() <- "Exit"
	channel.Close()
}
```

You will find that this code will only print `Do something`, and will not print `Exit`. Additionally, at this moment ch is already closed, and there is no way to wait for the consumer (channelHandler) to complete.

----

If we add the Done method, the infinity code might look like this:

```go
type Channel[T any] struct {
	input, output chan T
	length        chan int
	buffer        []T
	once          sync.Once
	done          chan struct{}
}

func NewChannel[T any]() *Channel[T] {
	ch := &Channel[T]{
		input:  make(chan T),
		output: make(chan T),
		length: make(chan int),
		buffer: []T{},
		done:   make(chan struct{}),
	}
	go ch.infiniteBuffer()
	return ch
}

func (ch *Channel[T]) Done() <-chan struct{} {
	return ch.done
}

func (ch *Channel[T]) Close() {
	ch.once.Do(func() {
		close(ch.input)
		select {
		case ch.done <- struct{}{}:
		default:
		}
		close(ch.done)
	})
}
```

I'm not sure if this is what you want, or if this requirement should fall under the responsibilities of the infinity library.

**Comment by BlackHole1** [comment]
I suddenly feel that this shouldn't be the responsibility of the infinity library 😅, as this would increase the complexity of infinity and deviate from the original design philosophy of infinity (which is merely to solve the problem of channel blocking). The waiting of the consumer itself or other demands should be addressed by the developers themselves, instead of letting a library focused on channels resolve it.

I will close this issue.
BTW. Thank you for developing go-infinity-channel, it is very useful 👍.
